### ISSUE TITLE
urxvt is setgid utmp

### ISSUE THREAD

**Issue by Merovius** [Merovius/shellex#33]
Urxvt is setgid utmp in a recent versions. This causes ld.so to ignore LD_PRELOAD, which means we can't lie to the shell about how big the terminal really is, which breaks shellex. This _might_ be the cause of #30.

We need to figure out a way to deal with this. urxvt needs to be setgid utmp, so we need to find a way different from LD_PRELOADing into urxvt to make this work. Options might be:
1. Inject LD_PRELOAD into the shell and overwrite the TIOCGWINSZ ioctl (instead of the TIOCSWINSZ in urxvt) to lie to the shell instead. This might be the most practical option, though it means we need to be careful about cleaning this up in children started by shellex, so that this doesn't lead to unwanted side-effects (e.g. when starting a terminal with shellex)
2. Inject the preload-library into urxvt at a later stage from the perl-plugin. It is unclear whether this is practical.
3. Patch urxvt to allow overwriting the size reported via TIOCSWINSZ via the perl plugin API and getting that upstream. This means convincing upstream that this is a useful feature (and a dependency on a suitable version of urxvt).

**Comment by Merovius** [comment]
Another way that came to me over night (I also thought about a second one but forgot that one…):

4. Write a helper that sits between urxvt and zsh and that rewrites the respective ioctls. This would have the advantage over 1 or 2, that we could get rid of C completely (as we could write that in perl) and it would add even more control (as we would control the complete communication interface between urxvt and zsh).

**Comment by pseyfert** [comment]
I worked a bit on 1 and with printf debugging see that the correctly manipulated values for the window size arrive in zsh. A few observations:
 * LD_PRELOAD must indeed be unset very early, as the import of the configuration fails already when LD_PRELOAD is set. So unloading must happen [here](https://github.com/Merovius/shellex/blob/master/urxvt/shellex.in#L211).
 * zsh gets created and before the hook `on_start` is called from by urxvt. This means that the `SHELLEX_MAX_ROWS` environment variable is not present in the zsh environment. This can not be fixed by making `max_rows` in `preload/main.c` non-static, because it's an environment problem. I claim this would also affect approaches 2.
 * I set a reasonable default value of maximum 30 rows in `preload/main.c` Via the zsh variable `LISTMAX=0` I could verify that zsh believes this is the window size, because it asks whether it should list possible completions once reaching 30 rows.
The last item reveals a more severe issue, which renders all four solution useless (as far as I understood them and zsh's behaviour). If the window is large enough, completions get listed below the prompt (fine). If it isn't, zsh prints all possible completions and adds a new prompt *below the list*. Which messes up shellex: the window gets resized larger than the screen. This can be fixed in `sub on_add_lines` and `on_line_update` (I tried this, and shellex stays in reasonable size).
I have, at the moment, no sane treatment of cases where the prompt ends up below the list (which I want to avoid anyhow). Short lists seem to be treated correctly. A temporary hack, I was playing with is to set a realistic maximum window size in urxvt's resizeing hooks and "infinity" the preload module for TIOCGWINSZ, this way, the prompt stays on top, multiple hits of `tab` don't let the terminal scroll further, and the window shrinks correctly back. A problem is that the tab-completion suggestions get partially useless because they will never be seen.

It seems to me, one must configure the tab completion via the confs correctly (staying on top and highlighting the suggestions when going through them). I wonder if the preload library can be dropped alltogether by configuring zsh's tab completion.

NB: for debugging I realise it's helpful to just call `zsh -f` in a regular terminal to understand the tab completion behaviour.

**Comment by Merovius** [comment]
1. This can be solved by unsetting it in the initialization of the preloaded library itself. This guarantees that it gets loaded into exactly one process. Then one just has to make sure that it is the correct process (probably by changing the env command that urxvt executes to set it).
2. The environment is the simplest, but not the only way to communicate values to child-processes. There are plenty other, so don't worry too much about that, it's not really a problem. For example: Opening a pipe before the child is created (e.g. `on_init`) and put it's fd in an environment variable. Any  child process can then read the env-var and has a bi-directional communication channel.
3. Is your current state of work in the referenced commit? If so, I'm going to try it later, it's hard to get the details straight from your description :)

**Comment by pseyfert** [comment]
There's one more commit (pseyfert/shellex@e104dd1498be8221bce008b2a3139bf1d6860248) on the [workaround branch](/pseyfert/shellex/tree/workaround) that's relevant.
the shellex size that's used is in [shellex.in](/pseyfert/shellex/blob/workaround/shellex.in) while in [urxvt/shellex.in](/pseyfert/shellex/blob/workaround/urxvt/shellex.in) there's a detection if the value is too large.
